export const TestMaterials = [
    "Micro Silica / Silica Fumes",
    "Cement",
    "Structural Steel",
    "Coarse Aggregate",
    "Fine Aggregate",
    "Fly Ash",
    "Gypsum",
    "Hardened Concrete",
    "Reinforcement Steel Bars",
    "Soil",
    "Construction Water",
    "Bitumen",
    "Bituminous Mix",
    "Burnt clay bricks",
    "Cement Concrete Floor Tiles",
    "Ceramic Glazed Tiles",
    "Chequered Tiles",
    "Concrete Beams",
    "Concrete Core",
    "Concrete Cube & Cylinder",
    "Concrete Cylinder",
    "Concrete Design Mix",
    "Fly Ash Bricks",
    "Glazed Ceramic Tiles",
    "Fresh Concrete",
    "GSB / WMM",
    "Gypsum Plaster",
    "Kerb Stone",
    "Lime Stone / Sand Stone / Kota Stone",
    "Marble / Granite Stone",
    "Paver Block",
    "GI Barbered wire",
    "Vitrified Tiles",
    "Hollow Sections (Structural Steel)",
    "MS / GI Barbered wire",
    "MS Pipes (Tube)",
    "Steel Plates",
    "Steel Tubes and Pipes",
    "Tubular Steel Poles",
    "Rock",
    "Stones",
    "Concrete",
    "Hardened Concrete"
]